[package]
name = "name_to_handle_at_rs"
version = "2.0.0"
edition = "2021"
license-file = "LICENSE"
description = "Rust bindings for name_to_handle_at() and open_by_handle_at() system calls in Linux"
repository = "https://github.com/ChrysoliteAzalea/name_to_handle_at_rs"
readme = "README.md"

[dependencies]
bitflags = "2.6.0"

[build-dependencies]
bindgen = "0.71.1"

[dev-dependencies]
libc = "0.2.158"

[[test]]
name = "test"
path = "test/test.rs"
